apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
      - name: webassets
        persistentVolumeClaim:
          claimName: plwebassets
      - name: data
        persistentVolumeClaim:
          claimName: plwebdata
      containers:
        - name: app
          image: localhost:32000/plweb:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          # ports:
          # - containerPort: 9000
          #   protocol: TCP
          envFrom:
          - configMapRef:
              name: plweb-config
          - secretRef:
              name: postgressecret
          - secretRef:
              name: app-secret
          volumeMounts:
          - mountPath: /var/www/html
            name: webassets
          - mountPath: /code/data
            name: data
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: dbvolume
        persistentVolumeClaim:
          claimName: plwebdb
      containers:
        - name: db
          image: postgres:alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
          - containerPort: 5432
            protocol: TCP
          envFrom:
          - configMapRef:
              name: plweb-config
          - secretRef:
              name: postgressecret
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: dbvolume
