apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plweb-ingress
  namespace: plweb
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  ingressClassName: public
  tls:
  - hosts:
    - youtube.wieru.com
    secretName: tls-secret
  rules:
  - host: youtube.wieru.com
    http: 
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-proxy-svc
              port:
                number: 80